skills for proofs
ProvedCode/frontend pull request #103
Opened 2023-05-19 13:48 UTC by daniilievtukhov

closwd #102

2023-05-19 21:28 UTC, Ruslanchik01 requested changes

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +        skills: edit === null ? "" : [],
no sense to use ternary operator, anyway it will be empty value

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +    useEffect(() => {
firstly you should initialize variables and then you can use useEffect

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +    const [newArray, setNewArray] = useState([]);
no sense to create new "useState", you can reuse currentSkills

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +                .then((response) => {
don't use response, then why you call it

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +        const uniqueSkillId = skillId.filter((id) => {
use hook "useCallback" and don't understand meaning of this function

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +    function writeSkills(data) {
useCallback

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +    const { user, talentsProofs, setTalentsProofs } = useContext(UserContext);
no sense to call user too, cause you use it only for user.id, that was initialize also in props

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +                    setMySkills(response);
you can reuse state "skills", delete this state or use in other situation

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +                                isMulti={isMulti}
you can write true, don't create variable

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/components/CustomClearIndicator/CustomClearIndicator.jsx
> +                        className="clear-indicator"
is this necessary class?

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/TalentData/TalentData.jsx
> +                {/* <div
I think you can delete this part

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/context/UserContext/UserContext.jsx
> +    const [mySkills, setMySkills] = useState({});
did you use it?

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/services/api-services.js
> +    async getProfileSkills(id, idProof, token) {
use more correct names like getProofSkills

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/services/api-services.js
> +    async addProfileSkills(id, idProof, token, skills) {
same

2023-05-19 21:28 UTC, Ruslanchik01 commented on src/services/api-services.js
> +    async deleteProfileSkills(id, idProof, token, skillId) {
same

2023-05-20 09:28 UTC, daniilievtukhov commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +                .then((response) => {
this u added)) ok, i'll remove response)

2023-05-20 14:52 UTC, Ruslanchik01 approved these changes

2023-05-20 16:02 UTC, merged