Added page of common proofs and realised filter of them
ProvedCode/frontend pull request #65
Opened 2023-04-12 13:53 UTC by whoisalex1W

I've created page of common proofs all the talents. Also implemented filter of them by date. 
#56

2023-04-12 14:00 UTC, Ruslanchik01 approved these changes

2023-04-12 14:00 UTC, Ruslanchik01 commented on src/context/UserContext/UserContext.jsx
> +    const [auth, setAuth] = useState(true);
Set to false

2023-04-12 14:28 UTC, daniilievtukhov commented on src/components/ListProofsPage/ListProofsPage.jsx
> +        setProofs(filter(proofs).reverse());
call the function filter on this method to have less lines of code ))

2023-04-12 15:04 UTC, IhorKopieichykov requested changes

2023-04-12 15:04 UTC, IhorKopieichykov commented on src/components/Layout/Header/Header.jsx
> +                            <Link to={`/${title.toLocaleLowerCase()}`}>
Remove child unnecessary link

2023-04-12 15:04 UTC, IhorKopieichykov commented on src/components/ListProofsPage/ListProofsPage.jsx
> +import s from "../ListProofsPage/ListProofsPage.module.scss";
Fix the import

2023-04-12 15:04 UTC, IhorKopieichykov commented on src/components/ListProofsPage/ListProofsPage.jsx
> +    const filter = (proofs) => {
```suggestion
    const filterByDateAsc = (proofs) => {
```

2023-04-12 15:04 UTC, IhorKopieichykov commented on src/components/ListProofsPage/ListProofsPage.jsx
Make two separate methods for filtering proofs array and remove redundant set methods

2023-04-12 20:21 UTC, daniilievtukhov approved these changes

2023-04-13 07:30 UTC, Ruslanchik01 approved these changes

2023-04-13 07:37 UTC, IhorKopieichykov approved these changes

2023-04-13 07:40 UTC, merged