adding personal proofs
ProvedCode/frontend pull request #74
Opened 2023-04-22 13:54 UTC by daniilievtukhov

closed #73

2023-04-22 14:59 UTC, Ruslanchik01 requested changes

2023-04-22 14:59 UTC, Ruslanchik01 commented on src/components/ProfilePage/ProfilePage.jsx
> +    const [isRotated, setIsRotated] = useState(false);
useless state u can do everything by state "proofsFormActive"

2023-04-22 14:59 UTC, Ruslanchik01 commented on src/components/ProfilePage/ProfilePage.jsx
> +                        active={proofsFormActive}
better to use same names

2023-04-22 14:59 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +import { Textarea } from "../../../../shared/components";
Update to single import

2023-04-22 14:59 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +import { UserContext } from "../../../../context/UserContext";
No sense to use UserContex. You can give props from parent

2023-04-22 14:59 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +                    const allProofs = [...talentsProofs, proof];
You can use previous state instead of create constant
```suggestion
                    setTalentsProofs((prev)=>[...prev, proof]);
```

2023-04-22 14:59 UTC, Ruslanchik01 commented on src/components/ProfilePage/ProfilePage.jsx
> +                            setproofsFormActive(!proofsFormActive);
Better to use previous state than write like this
```suggestion
                            setproofsFormActive((prev)=>!prev);
```

2023-04-22 14:59 UTC, Ruslanchik01 commented on src/shared/components/Textarea/Textarea.module.scss
> +    font-size: 22px !important;
It is better change styles localy

2023-04-22 14:59 UTC, Ruslanchik01 commented on src/components/ProfilePage/ProfilePage.module.scss
> +    width: 4%;
height and width better define with constant dimension like "px"

2023-04-23 11:29 UTC, whoisalex1W approved these changes

2023-04-23 11:40 UTC, whoisalex1W approved these changes

2023-04-23 11:58 UTC, Ruslanchik01 requested changes

2023-04-23 11:58 UTC, Ruslanchik01 commented on src/components/ProfilePage/ProfilePage.jsx
> +    const [active, setActive] = useState(false);
Active what? Use more specific names

2023-04-23 11:58 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +import { UserContext } from "../../../../context/UserContext";
Delete unused import

2023-04-23 11:58 UTC, Ruslanchik01 commented on src/components/ProfilePage/ProfilePage.jsx
> +                    <AddingProofsForm active={active} setActive={setActive} />
These props don't correspond to received in component
```suggestion
                    <AddingProofsForm active={active} setActive={setActive}  user={user} token={token}/>
```

2023-04-23 11:58 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/AddingProofsForm/AddingProofsForm.jsx
> +                    <textarea
Use shared component

2023-04-23 13:20 UTC, Ruslanchik01 approved these changes

2023-04-23 13:22 UTC, merged