fixed all bugs
ProvedCode/frontend pull request #78
Opened 2023-04-25 09:15 UTC by daniilievtukhov

fixed bugs

2023-04-25 10:18 UTC, Ruslanchik01 commented
Don't work manual control (change link) in proof pagination

2023-04-25 10:20 UTC, Ruslanchik01 commented
There are no deleting session after logout
There are no updating session after log in

2023-04-25 10:22 UTC, Ruslanchik01 commented
Proof block corner not working on hover

2023-04-25 10:22 UTC, Ruslanchik01 requested changes

2023-04-25 10:22 UTC, Ruslanchik01 commented on src/components/ProfilePage/ProfilePage.jsx
> +        sessionStorage.setItem("profile", JSON.stringify(profile));
No need to give whole 'profile' into session

2023-04-25 10:22 UTC, Ruslanchik01 commented on src/components/Layout/AuthModal/components/Register/Register.jsx
> +                    sessionStorage.setItem("profile", JSON.stringify(newUser));
You can change only name and last name

2023-04-25 10:22 UTC, Ruslanchik01 commented on src/components/ProfilePage/components/TalentData/TalentData.jsx
> +    sessionStorage.setItem("profile", JSON.stringify(profile));
delete this row

2023-04-25 18:38 UTC, Ruslanchik01 reviewed
Required some deleting rows: )

2023-04-26 08:51 UTC, whoisalex1W commented on src/components/ProfilePage/ProfilePage.jsx
> +                        // });
Remove these lines

2023-04-26 10:54 UTC, merged