edit+delete sponsor
ProvedCode/frontend pull request #97
Opened 2023-05-10 18:52 UTC by daniilievtukhov

closed #89 #88

2023-05-10 21:08 UTC, Ruslanchik01 requested changes

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/SponsorPage/SponsorPage.jsx
> +    }, [editting, navigate, location.pathname, location.search]);
Why you write same thing 2nd time, look at rows 29-33

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/SponsorPage/SponsorPage.jsx
> +                        setKudos(kudos + parseInt(numberKudos.kudos));
use previous state to change this constant
```suggestion
                        setKudos((prev)=> prev + parseInt(numberKudos.kudos));
```

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/SponsorPage/SponsorPage.jsx
> +                        setKudos(kudos + parseInt(numberKudos.kudos));
use previous state to change this constant
```suggestion
                        setKudos((prev)=> prev + parseInt(numberKudos.kudos));
```

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/Layout/Header/Header.jsx
> +    }, [user.id, kudos.amount]);
There is no such key in kudos (state)

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/SponsorPage/SponsorPage.jsx
> +            setNumberKudos({ kudos: kudos?.amount, error: "", state: true });
There is no such kudos.amount

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/SponsorPage/components/SponsorAbout/SponsorAbout.jsx
> +        profile,
Don't use this prop, so no sense to transfer it

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/SponsorPage/components/SponsorData/SponsorData.jsx
> +        profile,
You don't transfer this prop in parent component and don't use in this

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/SponsorPage/SponsorPage.jsx
> +        user,
Why you transfer it, if it won't be used

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/SponsorPage/SponsorPage.jsx
> +        state,
same problem

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/SponsorPage/SponsorPage.jsx
> +    const [state, setState] = useState(0);
useless state, is never used

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/SponsorPage/SponsorPage.jsx
> +                            amount: numberKudos.kudos,
You never use this value of profile

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/SponsorPage/components/SponsorAbout/SponsorAbout.jsx
> +    useImperativeHandle,
Unused import

2023-05-10 21:08 UTC, Ruslanchik01 commented on src/components/SponsorPage/components/SponsorAbout/SponsorAbout.jsx
> +export const SponsorAbout = forwardRef((props, ref) => {
No sense to use forwardRef

2023-05-11 09:11 UTC, whoisalex1W approved these changes

2023-05-11 09:16 UTC, Ruslanchik01 commented on src/components/SponsorPage/SponsorPage.jsx
> +            setNumberKudos({ kudos: kudos?.amount, error: "", state: true });
> There is no such kudos.amount

dont resolved

2023-05-11 09:16 UTC, Ruslanchik01 commented on src/components/SponsorPage/SponsorPage.jsx
> +                            amount: numberKudos.kudos,
> You never use this value of profile

don't resolved

2023-05-11 09:21 UTC, Ruslanchik01 requested changes

2023-05-11 09:21 UTC, Ruslanchik01 commented on src/components/SponsorPage/components/SponsorAbout/SponsorAbout.jsx
> +import React, { forwardRef } from "react";
delete forwardRef

2023-05-11 10:07 UTC, merged