94 sponsor kudos
ProvedCode/frontend pull request #99
Opened 2023-05-15 12:15 UTC by daniilievtukhov

fixed bugs from #98

2023-05-15 14:12 UTC, Ruslanchik01 requested changes

2023-05-15 14:12 UTC, Ruslanchik01 commented on src/components/ListProofsPage/ListProofsPage.jsx
> +                            <div className={s.kudos_parent}>
You can't enter tag `<div>` into tag `<p>`

2023-05-15 14:12 UTC, Ruslanchik01 commented on src/components/ListProofsPage/ListProofsPage.jsx
> +                                    max={kudos}
useless attribute without attribute "type='number' " or delete this attribute at all
`type=number
max={kudos}
min=0`

2023-05-15 14:13 UTC, Ruslanchik01 commented
please add full number of kudoses

2023-05-16 08:33 UTC, whoisalex1W approved these changes

2023-05-16 09:32 UTC, merged